harvest_time:
  # == bonemeal ============================================
  bonemeal_disabled:
    materials:
      - CROPS
      - CARROT
      - POTATO
      - PUMPKIN_STEM
      - MELON_STEM
      - SAPLING
      - COCOA

  # == seasonal growth =====================================
  seasonal:
    days_in_seasonal_year: 16
    crop_growth_check_material: WATCH
    rainfall_control:
      enabled: true
      MILD:
        frequency: 0.50
        rainfall_chance: 0.25
      DROUGHT:
        frequency: 0.25
        rainfall_chance: 0.0625
      MONSOON:
        frequency: 0.25
        rainfall_chance: 0.75

  # == farmland and harvesting =============================
  # -- farmland creation -----------------------------------
  farmland_creation:
    enabled: true
 
    block_type: CLAY
    block_count: 8

    tool_time:
      WOOD_HOE: 7.0
      STONE_HOE: 6.0
      IRON_HOE: 5.0
      DIAMOND_HOE: 3.0
      GOLD_HOE: 4.0

  # -- seasonal crop tending -------------------------------
  tending:
    radius: 2
    base_time: 10.0
    tool_multipliers:
      WOOD_HOE: 1.0
      STONE_HOE: 0.9
      IRON_HOE: 0.8
      DIAMOND_HOE: 0.5
      GOLD_HOE: 0.6

  # == bonuses =============================================
  # -- fresh water -----------------------------------------
  fresh_water:
    biome:
      enabled: true
      min_y: 63
      max_y: 68
      radius: 5
      biomes: [RIVER, FROZEN_RIVER]

    rainfall:
      enabled: true

  seasonal_rainfall_control:
    enable: true
    DROUGHT: 0.0625
    NORMAL: 0.25
    MONSOON: 0.75

  # -- regional bonuses ------------------------------------
  regional:
    enabled: true
    seed: ABBA

    nutrients:
      enabled: true
      region_size: 500.0
      variation_scale: 10000.0
      multipliers:
        FAIR:
          FAIR: 1.25
          VERY_FAIR: 1.0
          FOUL: 0.75
          VERY_FOUL: 0.5
        FOUL:
          FAIR: 0.75
          VERY_FAIR: 0.5
          FOUL: 1.0
          VERY_FOUL: 1.25  

    ph:
      enabled: true
      region_size: 500.0
      variation_scale: 10000.0
      multipliers:
        ACIDIC:
          ACIDIC: 1.0
          VERY_ACIDIC: 1.25
          NEUTRAL: 0.75
          VERY_NEUTRAL: 0.75
          BASIC: 0.5
          VERY_BASIC: 0.25
        NEUTRAL:
          ACIDIC: 0.75
          VERY_ACIDIC: 0.5
          NEUTRAL: 1.0
          VERY_NEUTRAL: 1.25
          BASIC: 0.75
          VERY_BASIC: 0.5
        BASIC:
          ACIDIC: 0.5
          VERY_ACIDIC: 0.25
          NEUTRAL: 0.75
          VERY_NEUTRAL: 0.75
          BASIC: 1.0
          VERY_BASIC: 1.25

    compactness:
      enabled: true
      region_size: 500.0
      variation_scale: 10000.0
      multipliers:
        LOOSE:
          LOOSE: 1.0
          VERY_LOOSE: 1.25
          COMPACT: 0.75
          VERY_COMPACT: 0.5
        COMPACT:
          LOOSE: 0.5
          VERY_LOOSE: 0.75
          COMPACT: 1.0
          VERY_COMPACT: 1.25

  # -- biome aliases ---------------------------------------
  biome_aliases:
    cold_grassland: [ICE_PLAINS]
    cold_forest: [TAIGA, TAIGA_HILLS]
    cold_mountain: [ICE_MOUNTAINS]

    temperate_grassland: [PLAINS]
    temperate_forest: [FOREST, FOREST_HILLS]
    temperate_mountain: [EXTREME_HILLS, SMALL_MOUNTAINS]
    temperate_wet: [SWAMPLAND, BEACH]

    tropical_desert: [DESERT, DESERT_HILLS]
    tropical_rainforest: [JUNGLE, JUNGLE_HILLS]

    water: [OCEAN, FROZEN_OCEAN, RIVER, FROZEN_RIVER]

    mushroom: [MUSHROOM_ISLAND, MUSHROOM_SHORE]
    alien: [HELL, SKY]

  # == crop listings =======================================
  seasonal_crop_list:
    block_CROPS:
      requires_sunlight: true
      start_day: 3
      max_stage_difference: 2

      base_tending_time: 5.0

      custom_yield:
        base_yield: 0.25

        fresh_water:
          multiplier: 4.0

        regional:
          nutrients: FAIR
          ph: ACIDIC
          compactness: LOOSE

        biome:
          cold_grassland: 0.125
          cold_forest: 0.125
          cold_mountain: 0.125
          temperate_grassland: 1.0
          temperate_forest: 0.75
          temperate_mountain: 0.125
          temperate_wet: 0.125
          tropical_desert: 0.75
          tropical_rainforest: 0.125
          water: 0.0
          mushroom: 0.125
          HELL: 0.0
          SKY: 0.125

    block_CARROT:
      requires_sunlight: true
      start_day: 3
      max_stage_difference: 1

      custom_yield:
        base_yield: 0.25

        fresh_water:
          multiplier: 4.0

        regional:
          nutrients: FAIR
          ph: ACIDIC
          compactness: COMPACT

        biome:
          cold_grassland: 0.125
          cold_forest: 0.125
          cold_mountain: 0.125
          temperate_grassland: 0.125
          temperate_forest: 0.5
          temperate_mountain: 0.125
          SWAMPLAND: 0.75
          BEACH: 0.125
          tropical_desert: 0.125
          tropical_rainforest: 1.0
          water: 0.0
          mushroom: 0.125
          HELL: 0.0
          SKY: 0.0

    block_POTATO:
      requires_sunlight: true
      start_day: 3
      max_stage_difference: 3

      base_tending_time: 5.0

      custom_yield:
        base_yield: 0.5

        fresh_water:
          multiplier: 2.0

        regional:
          nutrients: FAIR
          ph: NEUTRAL
          compactness: NONE

        biome:
          cold_grassland: 0.125
          cold_forest: 0.125
          cold_mountain: 0.75
          temperate_grassland: 0.5
          temperate_forest: 0.5
          temperate_mountain: 1.0
          temperate_wet: 0.125
          tropical_desert: 0.125
          tropical_rainforest: 0.125
          water: 0.0
          mushroom: 0.125
          HELL: 0.0
          SKY: 0.25

    # --------------------------------------------------------
    block_PUMPKIN_STEM:
      requires_sunlight: true
      start_day: 5
      max_stage_difference: 2

      base_tending_time: 5.0

      custom_yield:
        base_yield: 0.25

        fresh_water:
          multiplier: 4.0

        regional:
          nutrients: FOUL
          ph: BASIC
          compactness: COMPACT

        biome:
          cold_grassland: 0.75
          cold_forest: 1.0
          cold_mountain: 0.5
          temperate_grassland: 0.125
          temperate_forest: 0.25
          temperate_mountain: 0.25
          temperate_wet: 0.125
          tropical_desert: 0.0
          tropical_rainforest: 0.0
          water: 0.0
          mushroom: 0.0
          HELL: 0.0
          SKY: 0.0

    block_MELON_STEM:
      requires_sunlight: true
      start_day: 5
      max_stage_difference: 2

      base_tending_time: 5.0

      custom_yield:
        base_yield: 0.125

        fresh_water:
            multiplier: 8.0

        regional:
          nutrients: FAIR
          ph: BASIC
          compactness: LOOSE

        biome:
          cold_grassland: 0.0
          cold_forest: 0.0
          cold_mountain: 0.0
          temperate_grassland: 0.125
          temperate_forest: 0.125
          temperate_mountain: 0.125
          SWAMPLAND: 1.0
          BEACH: 0.125
          tropical_desert: 0.0
          tropical_rainforest: 0.75
          water: 0.0
          mushroom: 0.125
          HELL: 0.0
          SKY: 0.0

    # --------------------------------------------------------
    block_NETHER_WARTS:
      requires_sunlight: true
      start_day: 10
      max_stage_difference: 2

      base_tending_time: 5.0

      custom_yield:
        base_yield: 0.5

        fresh_water:
          multiplier: 2.0

        fertilizer_block:
          block_type: SOUL_SAND
          block_count: 16
          block_offset: 2
          multiplier: 1.5

        regional:
          nutrients: FAIR
          ph: NEUTRAL
          compactness: NONE

        biome:
          DEFAULT: 0.0
          tropical_rainforest: 0.125
          mushroom: 1.0
          HELL: 0.75

    block_COCOA:
      requires_sunlight: true
      start_day: 7
      max_stage_difference: 2

      base_tending_time: 5.0

      custom_yield:
        base_yield: 0.125

        fresh_water:
          multiplier: 8.0

        fertilizer_block:
          block_type: VINE
          block_count: 16
          block_offset: 1
          multiplier: 1.5

        regional:
          nutrients: FAIR
          ph: NEUTRAL
          compactness: NONE

        biome:
          DEFAULT: 0.0
          SWAMPLAND: 0.125
          tropical_rainforest: 1.0
          mushroom: 0.125
    
  chance_crop_list:
    # == CHANCE GROWTH =====================================
    # -- blocks --------------------------------------------
    block_MELON_BLOCK:
      requires_sunlight: false
      base_chance: 0.0

    block_PUMPKIN:
      requires_sunlight: false
      base_chance: 0.0

    # -- trees ---------------------------------------------
    tree_TREE:
      requires_sunlight: true
      base_chance: 1.0
  
    # -- breeding ------------------------------------------
        
    # -- eggs ----------------------------------------------
    # -- fishing -------------------------------------------