harvest_time:
  # == plugin interaction ==================================
  interaction:
    crop_growth_check_material: WATCH
    crop_yield_check_material: COMPASS

  # == bonemeal ============================================
  bonemeal_disabled:
    materials:
      - CROPS
      - CARROT
      - POTATO
      - PUMPKIN_STEM
      - MELON_STEM
      - SAPLING
      - COCOA

  # == farmland ============================================
  farmland_creation:
    enabled: true
 
    block_type: CLAY
    block_count: 8

    tool_time:
      WOOD_HOE: 7.0
      STONE_HOE: 6.0
      IRON_HOE: 5.0
      DIAMOND_HOE: 3.0
      GOLD_HOE: 4.0

  # == seasonal growth =====================================
  seasonal:
    days_in_seasonal_year: 20
    rainfall_control:
      enabled: true
      seed: Mt.Augusta
      MILD:
        frequency: 0.50
        rainfall_chance: 0.5
      DROUGHT:
        frequency: 0.25
        rainfall_chance: 0.125
      MONSOON:
        frequency: 0.25
        rainfall_chance: 0.875

  # -- seasonal crop tending -------------------------------
  tending:
    radius: 2
    tool_times:
      WOOD_HOE: 10.0
      STONE_HOE: 9.0
      IRON_HOE: 8.0
      DIAMOND_HOE: 5.0
      GOLD_HOE: 6.0

  # == global environment configuration ====================
  # -- fresh water -----------------------------------------
  fresh_water:
    biome:
      enabled: true
      min_y: 62
      max_y: 68
      radius: 5
      biomes: [RIVER, FROZEN_RIVER]

    rainfall:
      enabled: true

  # -- regional multiplier ---------------------------------
  regional:
    enabled: true
    seed: Columbia
    cell_size: 1000.0
    variation_size: 5000.0

    nutrients:
      multipliers:
        FAIR:
          FAIR: 1.25
          VERY_FAIR: 1.0
          FOUL: 0.75
          VERY_FOUL: 0.5
        FOUL:
          FAIR: 0.75
          VERY_FAIR: 0.5
          FOUL: 1.0
          VERY_FOUL: 1.25  

    ph:
      multipliers:
        ACIDIC:
          ACIDIC: 1.0
          VERY_ACIDIC: 1.25
          NEUTRAL: 0.75
          VERY_NEUTRAL: 0.75
          BASIC: 0.5
          VERY_BASIC: 0.25
        NEUTRAL:
          ACIDIC: 0.75
          VERY_ACIDIC: 0.5
          NEUTRAL: 1.0
          VERY_NEUTRAL: 1.25
          BASIC: 0.75
          VERY_BASIC: 0.5
        BASIC:
          ACIDIC: 0.5
          VERY_ACIDIC: 0.25
          NEUTRAL: 0.75
          VERY_NEUTRAL: 0.75
          BASIC: 1.0
          VERY_BASIC: 1.25

    compactness:
      multipliers:
        LOOSE:
          LOOSE: 1.0
          VERY_LOOSE: 1.25
          COMPACT: 0.75
          VERY_COMPACT: 0.5
        COMPACT:
          LOOSE: 0.5
          VERY_LOOSE: 0.75
          COMPACT: 1.0
          VERY_COMPACT: 1.25

  # -- biome aliases ---------------------------------------
  biome_aliases:
    cold_grassland: [ICE_PLAINS]
    cold_forest: [TAIGA, TAIGA_HILLS]
    cold_mountain: [ICE_MOUNTAINS]

    temperate_grassland: [PLAINS]
    temperate_forest: [FOREST, FOREST_HILLS]
    temperate_mountain: [EXTREME_HILLS, SMALL_MOUNTAINS]
    temperate_swamp: [SWAMPLAND]

    tropical_desert: [DESERT, DESERT_HILLS]
    tropical_rainforest: [JUNGLE, JUNGLE_HILLS]

    water: [OCEAN, FROZEN_OCEAN, RIVER, FROZEN_RIVER]
    beach: [BEACH]

    mushroom: [MUSHROOM_ISLAND, MUSHROOM_SHORE]
    hell: [HELL]
    sky: [SKY]

  # == crop listings =======================================
  seasonal_crop_list:
    block_CROPS:
      start_day: 4
      max_stage_difference: 2

      custom_yield:
        base_yield: 0.0625

        sunlight:
          min_sunlight_level: 15
          glowstone_lighting_enabled: true
          multiplier: 4.0

        fresh_water:
          irrigation_multiplier: 4.0
          rainfall_multiplier: 4.0

        regional:
          nutrients: FAIR
          ph: ACIDIC
          compactness: LOOSE

        biome:
          cold_grassland: 0.125
          cold_forest: 0.125
          cold_mountain: 0.125

          temperate_grassland: 1.0
          temperate_forest: 0.75
          temperate_mountain: 0.125
          temperate_swamp: 0.125

          tropical_desert: 0.75
          tropical_rainforest: 0.125

          water: 0.125
          beach: 0.125

          mushroom: 0.0
          HELL: 0.0
          SKY: 0.0

    block_CARROT:
      start_day: 8
      max_stage_difference: 1

      custom_yield:
        base_yield: 0.0625

        sunlight:
          min_sunlight_level: 15
          glowstone_lighting_enabled: true
          multiplier: 4.0

        fresh_water:
          irrigation_multiplier: 4.0
          rainfall_multiplier: 4.0

        regional:
          nutrients: FAIR
          ph: ACIDIC
          compactness: COMPACT

        biome:
          cold_grassland: 0.125
          cold_forest: 0.125
          cold_mountain: 0.125

          temperate_grassland: 0.75
          temperate_forest: 1.0
          temperate_mountain: 0.125
          temperate_swamp: 0.125

          tropical_desert: 0.125
          tropical_rainforest: 0.75

          water: 0.125
          beach: 0.125

          mushroom: 0.0
          HELL: 0.0
          SKY: 0.0

    block_POTATO:
      start_day: 8
      max_stage_difference: 3

      custom_yield:
        base_yield: 0.125

        sunlight:
          min_sunlight_level: 15
          glowstone_lighting_enabled: true
          multiplier: 4.0

        fresh_water:
          irrigation_multiplier: 2.0
          rainfall_multiplier: 2.0

        regional:
          nutrients: FAIR
          ph: NEUTRAL
          compactness: LOOSE

        biome:
          cold_grassland: 0.125
          cold_forest: 0.125
          cold_mountain: 0.75

          temperate_grassland: 0.75
          temperate_forest: 0.75
          temperate_mountain: 1.0
          temperate_swamp: 0.75

          tropical_desert: 0.125
          tropical_rainforest: 0.125

          water: 0.125
          beach: 0.125

          mushroom: 0.0
          HELL: 0.0
          SKY: 0.125

    # --------------------------------------------------------
    block_PUMPKIN_STEM:
      start_day: 8
      max_stage_difference: 2

      custom_yield:
        base_yield: 0.0625

        sunlight:
          min_sunlight_level: 15
          glowstone_lighting_enabled: true
          multiplier: 4.0

        fresh_water:
          irrigation_multiplier: 4.0
          rainfall_multiplier: 4.0

        regional:
          nutrients: FOUL
          ph: BASIC
          compactness: COMPACT

        biome:
          cold_grassland: 0.75
          cold_forest: 1.0
          cold_mountain: 0.75

          temperate_grassland: 0.125
          temperate_forest: 0.75
          temperate_mountain: 0.125
          temperate_swamp: 0.125

          tropical_desert: 0.0
          tropical_rainforest: 0.0

          water: 0.0
          beach: 0.0

          mushroom: 0.0
          HELL: 0.0
          SKY: 0.125

    block_MELON_STEM:
      start_day: 4
      max_stage_difference: 2

      custom_yield:
        base_yield: 0.0625

        sunlight:
          min_sunlight_level: 15
          glowstone_lighting_enabled: true
          multiplier: 4.0

        fresh_water:
          irrigation_multiplier: 4.0
          rainfall_multiplier: 4.0

        regional:
          nutrients: FAIR
          ph: BASIC
          compactness: LOOSE

        biome:
          cold_grassland: 0.0
          cold_forest: 0.0
          cold_mountain: 0.0

          temperate_grassland: 0.125
          temperate_forest: 0.125
          temperate_mountain: 0.0
          temperate_swamp: 1.0

          tropical_desert: 0.125
          tropical_rainforest: 0.75

          water: 0.0
          beach: 0.0

          mushroom: 0.0
          HELL: 0.0
          SKY: 0.0

    # --------------------------------------------------------
    block_NETHER_WARTS:
      start_day: 13
      max_stage_difference: 2

      custom_yield:
        base_yield: 0.0625

        sunlight:
          min_sunlight_level: 15
          glowstone_lighting_enabled: true
          multiplier: 4.0

        fresh_water:
          irrigation_multiplier: 1.0
          rainfall_multiplier: 4.0

        fertilizer_block:
          block_type: STATIONARY_LAVA
          block_count: 16
          block_offset: 2
          multiplier: 4.0

        regional:
          nutrients: FAIR
          ph: NEUTRAL
          compactness: COMPACT

        biome:
          DEFAULT: 0.0
          tropical_rainforest: 0.125
          mushroom: 0.75
          HELL: 1.0

    block_COCOA:
      start_day: 1
      max_stage_difference: 2

      base_tending_time: 5.0

      custom_yield:
        base_yield: 0.0625

        sunlight:
          min_sunlight_level: 15
          glowstone_lighting_enabled: true
          multiplier: 4.0

        fresh_water:
          irrigation_multiplier: 1.0
          rainfall_multiplier: 8.0

        fertilizer_block:
          block_type: VINE
          block_count: 16
          block_offset: 1
          multiplier: 4.0

        regional:
          nutrients: FAIR
          ph: NEUTRAL
          compactness: COMPACT

        biome:
          DEFAULT: 0.0
          SWAMPLAND: 0.125
          tropical_rainforest: 1.0
    
  chance_crop_list:
    # == CHANCE GROWTH =====================================
    # -- blocks --------------------------------------------
    block_MELON_BLOCK:
      base_chance: 0.0

    block_PUMPKIN:
      base_chance: 0.0

    # -- trees ---------------------------------------------
  
    # -- breeding ------------------------------------------

    # -- eggs ----------------------------------------------
    egg_hatching:
      base_chance: 0.0

    # -- fishing -------------------------------------------
    fishing:
      base_chance: 1.0

      biome:
        DEFAULT: 0.0
        water: 1.0