harvest_time:
  # == plugin interaction ==================================
  interaction:
    crop_growth_check_material: WATCH
    crop_yield_check_material: COMPASS

    sound_enabled: true

  # == bonemeal ============================================
  bonemeal_disabled:
    materials:
      - CROPS
      - CARROT
      - POTATO
      - PUMPKIN_STEM
      - MELON_STEM
      - SAPLING
      - COCOA

  # == farmland ============================================
  farmland_creation:
    enabled: true
 
    block_type: CLAY
    block_count: 8

    tool_time:
      WOOD_HOE: 7.0
      STONE_HOE: 6.0
      IRON_HOE: 5.0
      DIAMOND_HOE: 3.0
      GOLD_HOE: 4.0

  # == seasonal growth =====================================
  seasonal:
    # 86400000 ms in a RL day
    milliseconds_in_seasonal_day: 86400000
    days_in_seasonal_year: 16

  # == seasonal crop tending ===============================
  tending:
    tool_times:
      WOOD_HOE: 10.0
      STONE_HOE: 9.0
      IRON_HOE: 8.0
      DIAMOND_HOE: 5.0
      GOLD_HOE: 6.0

  # == global environment configuration ====================
  # -- fresh water -----------------------------------------
  fresh_water:
    biome:
      enabled: true
      min_y: 62
      max_y: 68
      radius: 5
      biomes: [RIVER, FROZEN_RIVER]

  # -- biome aliases ---------------------------------------
  biome_aliases:
    cold_grassland: [ICE_PLAINS]
    cold_forest: [TAIGA, TAIGA_HILLS]
    cold_mountain: [ICE_MOUNTAINS]

    temperate_grassland: [PLAINS]
    temperate_forest: [FOREST, FOREST_HILLS]
    temperate_mountain: [EXTREME_HILLS, SMALL_MOUNTAINS]
    temperate_swamp: [SWAMPLAND]

    tropical_desert: [DESERT, DESERT_HILLS]
    tropical_rainforest: [JUNGLE, JUNGLE_HILLS]

    water: [OCEAN, FROZEN_OCEAN, RIVER, FROZEN_RIVER]
    beach: [BEACH]

    mushroom: [MUSHROOM_ISLAND, MUSHROOM_SHORE]
    hell: [HELL]
    sky: [SKY]

  # == crop listings =======================================
  seasonal_crop_list:
    block_CROPS:
      start_day: 4
      max_stage_difference: 2

      custom_yield:
        base_yield: 0.0625

        sunlight:
          min_sunlight_level: 15
          multiplier: 4.0

        fresh_water:
          irrigation_multiplier: 4.0

        biome:
          cold_grassland: 0.125
          cold_forest: 0.125
          cold_mountain: 0.125

          temperate_grassland: 1.0
          temperate_forest: 0.75
          temperate_mountain: 0.125
          temperate_swamp: 0.125

          tropical_desert: 0.75
          tropical_rainforest: 0.125

          water: 0.125
          beach: 0.125

          mushroom: 0.0
          HELL: 0.0
          SKY: 0.0

    block_CARROT:
      start_day: 8
      max_stage_difference: 1

      custom_yield:
        base_yield: 0.0625

        sunlight:
          min_sunlight_level: 15
          multiplier: 4.0

        fresh_water:
          irrigation_multiplier: 4.0

        biome:
          cold_grassland: 0.125
          cold_forest: 0.125
          cold_mountain: 0.125

          temperate_grassland: 0.75
          temperate_forest: 1.0
          temperate_mountain: 0.125
          temperate_swamp: 0.125

          tropical_desert: 0.125
          tropical_rainforest: 0.75

          water: 0.125
          beach: 0.125

          mushroom: 0.0
          HELL: 0.0
          SKY: 0.0

    block_POTATO:
      start_day: 8
      max_stage_difference: 3

      custom_yield:
        base_yield: 0.125

        sunlight:
          min_sunlight_level: 15
          multiplier: 4.0

        fresh_water:
          irrigation_multiplier: 2.0

        biome:
          cold_grassland: 0.125
          cold_forest: 0.125
          cold_mountain: 0.75

          temperate_grassland: 0.75
          temperate_forest: 0.75
          temperate_mountain: 1.0
          temperate_swamp: 0.75

          tropical_desert: 0.125
          tropical_rainforest: 0.125

          water: 0.125
          beach: 0.125

          mushroom: 0.0
          HELL: 0.0
          SKY: 0.125

    # --------------------------------------------------------
    block_PUMPKIN_STEM:
      start_day: 8
      max_stage_difference: 2

      custom_yield:
        base_yield: 0.0625

        sunlight:
          min_sunlight_level: 15
          multiplier: 4.0

        fresh_water:
          irrigation_multiplier: 4.0

        biome:
          cold_grassland: 0.75
          cold_forest: 1.0
          cold_mountain: 0.75

          temperate_grassland: 0.125
          temperate_forest: 0.75
          temperate_mountain: 0.125
          temperate_swamp: 0.125

          tropical_desert: 0.0
          tropical_rainforest: 0.0

          water: 0.0
          beach: 0.0

          mushroom: 0.0
          HELL: 0.0
          SKY: 0.125

    block_MELON_STEM:
      start_day: 4
      max_stage_difference: 2

      custom_yield:
        base_yield: 0.0625

        sunlight:
          min_sunlight_level: 15
          multiplier: 4.0

        fresh_water:
          irrigation_multiplier: 4.0

        biome:
          cold_grassland: 0.0
          cold_forest: 0.0
          cold_mountain: 0.0

          temperate_grassland: 0.125
          temperate_forest: 0.125
          temperate_mountain: 0.0
          temperate_swamp: 1.0

          tropical_desert: 0.125
          tropical_rainforest: 0.75

          water: 0.0
          beach: 0.0

          mushroom: 0.0
          HELL: 0.0
          SKY: 0.0

    # --------------------------------------------------------
    block_NETHER_WARTS:
      start_day: 13
      max_stage_difference: 2

      custom_yield:
        base_yield: 0.0625

        sunlight:
          min_sunlight_level: 15
          multiplier: 4.0

        fresh_water:
          irrigation_multiplier: 1.0

        fertilizer_block:
          block_type: STATIONARY_LAVA
          block_count: 16
          block_offset: 2
          multiplier: 4.0

        biome:
          DEFAULT: 0.0
          tropical_rainforest: 0.125
          mushroom: 0.75
          HELL: 1.0

    block_COCOA:
      start_day: 1
      max_stage_difference: 2

      base_tending_time: 5.0

      custom_yield:
        base_yield: 0.0625

        sunlight:
          min_sunlight_level: 15
          multiplier: 4.0

        fresh_water:
          irrigation_multiplier: 1.0

        fertilizer_block:
          block_type: VINE
          block_count: 16
          block_offset: 1
          multiplier: 4.0

        biome:
          DEFAULT: 0.0
          SWAMPLAND: 0.125
          tropical_rainforest: 1.0
    
  chance_crop_list:
    # == CHANCE GROWTH =====================================
    # -- blocks --------------------------------------------
    block_MELON_BLOCK:
      base_chance: 0.0

    block_PUMPKIN:
      base_chance: 0.0

    # -- trees ---------------------------------------------
  
    # -- breeding ------------------------------------------

    # -- eggs ----------------------------------------------
    egg_hatching:
      base_chance: 0.0

    # -- fishing -------------------------------------------
    fishing:
      base_chance: 1.0

      biome:
        DEFAULT: 0.0
        water: 1.0